# Usa la imagen oficial de MySQL
FROM mysql:8.2

# Define las variables de entorno para la configuración de la base de datos
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=be-bolsadetrabajo-db
ENV MYSQL_USER=mysql
ENV MYSQL_PASSWORD=1234

# Copia el script de creación de tablas al directorio de inicio de la base de datos
COPY schema.sql /docker-entrypoint-initdb.d/

# Opcional: Cambia el juego de caracteres y el conjunto de collation si es necesario
ENV MYSQL_CHARSET=utf8
ENV MYSQL_COLLATION=utf8_unicode_ci
